### ISSUE TITLE
error passing

### ISSUE THREAD

**Issue by mcfrank** [mhtess/rwebppl#40]
hi guys, rwebppl is very useful! 

but as usual, debugging is quite hard. for example, every error starts with:

```
Error in run_webppl(program_code = program_code, program_file = program_file,  : 
  /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:237
    throw error;
    ^
```

and then occasionally another somewhat informative error will make its way to the top of the stack trace. But it would be super awesome if there were e.g. a line number associated with errors (or a code chunk or whatever).

**Comment by mhtess** [comment]
Thanks for contributing! When you encounter your next examples of good and bad error passing, can you put them here?

**Comment by mcfrank** [comment]
Sure - I didn't do so because they are not MWEs, they are just from the
broken thing I was playing with. That ok?

**Comment by mhtess** [comment]
That's fine for now. MWE are of course preferred

**Comment by hawkrobe** [comment]
For what it's worth, webppl itself has a number of remaining issues with error-passing as well (due to all the source transforms, see [#314](https://github.com/probmods/webppl/issues/314)). For rwebppl, I think the best we can do is make sure that the webppl errors make it to the r user. 

One improvement over this we might consider (even though it might currently be unworkable) is to map the line numbers from the webppl program to line numbers in the R program.

**Comment by mhtess** [comment]
I agree that the best we could hope for at the current stage is to get the webppl errors into r

**Comment by mcfrank** [comment]
so this one made me sad:  

```
Error in run_webppl(program_code = program_code, program_file = program_file,  : 
  /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:237
    throw error;
    ^

TypeError: Cannot read property 'value' of undefined
    at eval (eval at <anonymous> (/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:246:10), <anonymous>:220:50)
    at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/util.js:38:13
    at /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:214:14
    at runner (/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:223:37)
    at eval (eval at <anonymous> (/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:246:10), <anonymous>:6:17)
    at run (/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rwebppl/js/webppl/src/main.js:246:66)
    at Object.timeif (/Library/Frameworks/R.framework/Versions/3
```

from this:

```
// noise up feature
var noisy_feature = function (f) {
  return(flip(0.1) ? f : !f);
};

// sample concept
var concept = function () {
  return([flip(0.5), flip(0.5), flip(0.5)]);
};

// equals
var eq = function(x, y) {
  return(x == y);
};

// array eqals
var array_eq = function (x, y) {
  return(all(map2(eq, x, y)));
};

// return a noisy observation of a concept
var model = function() {
  var c = concept();
  factor(array_eq(map(noisy_feature, concept), 
                  [df[1].value, df[2].value, df[3].value])
         ? 0 : -Infinity) ;
  return(concept);
};

Infer({method: 'enumerate'}, model);
```

**Comment by mhtess** [comment]
What was `df`?

**Comment by mcfrank** [comment]
``` r
df <- data.frame(feature = c(1, 2, 3), 
                 value = c(TRUE, TRUE, TRUE))

webppl(program_file = "concept_learning.js", 
       data = df, 
       data_var = "df")
```

**Comment by hawkrobe** [comment]
Unfortunately, it looks like that's a `webppl` error:

<img width="527" alt="webpplerror" src="https://cloud.githubusercontent.com/assets/5262024/19131586/d201217a-8b04-11e6-9e88-1d4bd45dfd35.png">

**Comment by mhtess** [comment]
There are actually two errors in this code. The one that throws the error is because of `array_eq`, for reasons that are not clear to me. Replacing it with the underscore `_.isEqual` gets rid of the error.

The other bug is in your `model` code. You sample `c` from `concept()`, but then go on using `concept` (which is a function), as if it were `c` (an array).  It doesn't throw an error but it will return garbage.

**Comment by hawkrobe** [comment]
The [online editor](https://github.com/probmods/webppl-editor) has a feature that looks up and highlights the relevant characters in the program, but it gives exactly the same message if you run it in the console... So I'd open an issue over at the `webppl` repo.

**Comment by mhtess** [comment]
Oh, the third error is that you are indexing counting from 1. You should index counting from 0.

**Comment by hawkrobe** [comment]
@mhtess : I suspect @mcfrank was able to find the errors himself, the issue is just that the messages we spit out didn't help very much!

**Comment by mhtess** [comment]
Oh I see. Ya, I'm no expert on error messages, but isn't the error message that webppl is throwing the correct one to throw? (i.e., the one that shows up in the editor and console)

**Comment by hawkrobe** [comment]
Yep, it's the right error _text_, but the stack info that would tell you where in your code it's coming from is super baroque because of all the transforms. 

> But it would be super awesome if there were e.g. a line number associated with errors (or a code chunk or whatever).

This info is technically in the stack, but it's really gnarly to extract it, and almost impossible for the user to do visually (see editor issue [#10](https://github.com/probmods/webppl-editor/issues/10) for the strategy they ended up going with)

**Comment by mcfrank** [comment]
Ok, cool - yes, line number highlighting would totally be enough to be helpful. I guess the trouble in rwebppl is that you are essentially passing the program as a string?

And thanks for your faith that I did in fact debug those errors - eventually, I did. :)
